"server-only";
import './globals.css';
import AppContextProvider from '@/context/app-context';
import { Header } from '@/components/ui/Header';
import { ScrollLock } from '@/utils/stop-scroll';

export const metadata = {
  title: 'find map',
  description: 'Generated by create next app',
};

// do not cache this layout
export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Header />
          {children}
          <ScrollLock />
        </AppContextProvider>
      </body>
    </html >
  );
}
